# -*- coding: utf-8 -*-
"""Forecast bikeshare demand using time series models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQXiOT-BTmdz_4lx0SU9mLS2qpqpO2fZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

import warnings

warnings.filterwarnings('ignore')

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import pandas as pd # Ensure pandas is imported here for read_csv
import os

train_csv_path = '/content/train.csv'
test_csv_path = '/content/test.csv'

if os.path.exists(train_csv_path) and os.path.exists(test_csv_path):
    print(f"'{train_csv_path}' and '{test_csv_path}' found. Proceeding with data loading.")
    train = pd.read_csv(train_csv_path)
    test = pd.read_csv(test_csv_path)

    print(f"Train data shape: {train.shape}")
    print(f"Test data shape: {test.shape}")

    print("\nFirst 5 rows of train data:")
    display(train.head()) # Use display for better output in Colab
else:
    print(f"'{train_csv_path}' or '{test_csv_path}' not found. Please upload the 'train.csv' and 'test.csv' files to the '/content/' directory.")
    print("Once uploaded, run this cell again.")

import os

zip_file_path = '/kaggle/input/competitions/bike-sharing-demand'
if os.path.exists(zip_file_path):
    print(f"'{zip_file_path}' found. You can proceed with unzipping.")
else:
    print(f"'{zip_file_path}' not found. Please ensure it's uploaded to the correct location.")

from google.colab import drive
drive.mount('/content/drive')

train.sample(5)

test.sample(5)

train.info()

test.info()

train.describe().T

train.drop_duplicates(inplace= True)

import seaborn as sns
sns.boxplot(x='count', data=train, color='yellow')
plt.show()

from scipy.__config__ import show
sns.set_style('whitegrid')
sns.distplot(train['count'], color='blue')
plt.show

fields = [i for i in train]
fields=fields[5:9]
print(fields)

fig = plt.figure(figsize=(17,3))
for i,f in enumerate(fields):
  ax = fig.add_subplot(1,4,i+1)
  ax.scatter(train[f], train['count'])
  ax.set_title(f)
plt.tight_layout()

fig,axes = plt.subplots(nrows=2, ncols=2, figsize=(16,8))
fig.set_size_inches(20,10)

sns.boxplot(x='season', y='count', data=train, ax=axes[0,0])
sns.boxplot(x='holiday',y='count', data=train, ax=axes[0,1])
sns.boxplot(x='weather',y='count', data=train, ax=axes[1,0])
sns.boxplot(x='workingday',y='count', data=train, ax=axes[1,1])

fig, axs = plt.subplots(1,4)
fig.set_size_inches (20,5)
sns.lineplot(data=train, x="windspeed", y="count", ax=axs[1])
sns.lineplot(data=train, x="humidity", y="count", ax=axs[0])
sns.lineplot(data=train, x="temp", y="count", ax=axs[2])
sns.lineplot(data=train, x="workingday", y="count", ax=axs [3])

plt.figure(figsize=(10,10))
sns.heatmap(train.select_dtypes(include=np.number).corr(), vmin=-1, vmax=1, cmap='coolwarm', annot=True, square = True)

train['datetime']= pd.to_datetime(train['datetime'])
train['year'] = train['datetime'].dt.year
train['month'] = train['datetime'].dt
test['datetime']= pd.to_datetime(test['datetime'])
test['year'] = test['datetime'].dt.year
test['month'] = test['datetime'].dt

train.sample(5)

train.info()

test.sample(5)

test.info()



import pandas as pd

# Ensure train DataFrame is loaded and datetime column is processed if not already
# This part duplicates code from earlier cells to make this cell runnable in isolation if needed.
try:
    if 'train' not in locals() or not isinstance(train, pd.DataFrame) or 'datetime' not in train.columns:
        train = pd.read_csv("/content/train.csv")
        train['datetime'] = pd.to_datetime(train['datetime'])
except FileNotFoundError:
    print("Error: train.csv not found. Please ensure the dataset is unzipped at /content/.")
    raise

train['year'] = train['datetime'].dt.year
train['month'] = train['datetime'].dt.month
train['day'] = train['datetime'].dt.day
train['dayofweek']= train['datetime'].dt.dayofweek
train['hour'] = train['datetime'].dt.hour

train.sample(5)

train=train.drop(['datetime'], axis=1)
train= train.drop(['casual'], axis=1)
train= train.drop(['registered'], axis=1)

train.sample(5)

test['year'] = pd.to_datetime(test['datetime']).dt.year
test['month'] = pd.to_datetime(test['datetime']).dt.month
test['day'] = pd.to_datetime(test['datetime']).dt.day
test['dayofweek']= pd.to_datetime(test['datetime']).dt.dayofweek
test['hour'] = pd.to_datetime(test['datetime']).dt.hour

test=test.drop(['datetime'], axis=1)

test.sample(5)

train.info()

test.info()

fig, axes = plt.subplots (nrows=3, ncols=1)
fig.set_size_inches(10,15)
sns.barplot(data=train,x='year', y='count', ax=axes[0])
sns.barplot(data=train,x='month', y='count', ax=axes[1])
sns.barplot(data=train,x='hour', y='count', ax=axes [2], hue='dayofweek')

f, axes = plt.subplots(1, 1, figsize=(15,6))
sns.boxplot(data=train, y='count', x='hour', hue='workingday', ax=axes)
handles,_ = axes.get_legend_handles_labels()
axes.legend(handles, ['Not a Working Day', 'Working Day'])
plt.show()

import plotly.express as px

figl = px.bar(train, x="weather", y="count")
fig2 = px.bar(train, x="windspeed", y="count")
fig3 = px.bar(train, x="humidity", y="count")
fig4 = px.bar(train, x="temp", y="count")

figl.update_traces (marker_line_width=0)
fig2.update_traces (marker_line_width=0)
fig3.update_traces (marker_line_width=0)
fig4.update_traces (marker_line_width=0)

figl.show()
fig2.show()
fig3.show()
fig4.show()

f, axes = plt.subplots (nrows=1, ncols=1, figsize=(15,6))
group_month= pd.DataFrame(train.groupby(['month', 'workingday']) ['count'].mean()).reset_index()
sns.barplot(data=group_month, x='month', y='count', hue='workingday', ax=axes)
axes.set(xlabel='Month', ylabel='Count')
handles,_ = axes.get_legend_handles_labels()
axes.legend(handles, ['Not a Working Day', 'Working Day'])
plt.show()

sns.histplot(train['count'])

train['count']=np.log1p(train['count'])

sns.histplot(train['count'])

train=train[np.abs(train['count'])-train['count'].mean()<=(3*train['count'].std())]

sns.boxplot(x='count', data=train, color='lightgreen')
plt.show()

fig=plt.figure(figsize=(15,15))
for i,fl in enumerate(fields):
   for j,f2 in enumerate(fields):
       idx =i*len(fields)+j+1
       ax=fig.add_subplot(len(fields), len (fields), idx)
       ax.scatter(train[fl], train[f2])
       ax.set_ylabel(fl)
       ax.set_xlabel(f2)
plt.show()

drop_idx = train[(train['atemp']>20) & (train['atemp']<40) & (train['temp']>10) & (train['temp']<20)].index
train =train.drop(drop_idx)
from sklearn.preprocessing import MinMaxScaler
def scaling(df):
  scaler= MinMaxScaler()
  num_cols= ['temp', 'atemp', 'humidity', 'windspeed'] # Corrected: 'temp', 'atemp' should be separate strings
  df[num_cols]=scaler.fit_transform(df[num_cols])
  return df
train =scaling(train)
test = scaling(test)
train.sample(5)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(train.drop(['count'],axis=1),train['count'], test_size =0.3)

def rmsle(y,pred):
    log_y =np.log1p(y)
    log_pred=np.log1p(pred)
    squared_error = (log_y - log_pred)**2
    remsle =np.sqrt(np.mean(squared_error))
    return remsle

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import GridSearchCV

def evaluate(reg_cls,params=None):
    reg=reg_cls()
    if params:
       reg=GridSearchCV(reg,param_grid=params,refit = True)
    reg.fit(X_train, Y_train)
    pred=reg.predict(X_test)
    print(findmae(Y_test, pred))
    score =reg.score(X_test, Y_test)*100
    print(score)
    y_test_exp = np.expm1(Y_test)
    pred_exp=np.expm1(pred)

    print('\n',reg_cls)
    if params:
       print(reg.best_params_)
       reg=reg.best_estimator_
    print(rmsle(y_test_exp,pred_exp))
    return reg, pred_exp

from sklearn.metrics import mean_absolute_error as mae
def findmae(Y_test,pred):
    return mae(Y_test, pred)

print("--LinearRegression---")
lr_reg, pred_lr = evaluate (LinearRegression)
print("--Ridge--")
rg_reg, pred_rg = evaluate (Ridge)
print("---Lasso---")
ls_reg, pred_ls = evaluate (Lasso)
print("---Random ForestRegressor---")
rf_reg, pred_rf = evaluate (RandomForestRegressor)
print("----GradientBoosting Regressor-----")
gb_reg, pred_gb = evaluate (GradientBoostingRegressor)
print("---XGBRegressor--------")
xg_reg, pred_xg = evaluate (XGBRegressor)
print(". ---LGBMRegressor-")
lg_reg, pred_lg = evaluate (LGBMRegressor)
params ={'n_estimators': [100*i for i in range(1,6)]}
print("---XGBRegressor")
xg_reg, pred_xg = evaluate (XGBRegressor, params)
print("LGBMRegressor-----")
lg_reg, pred_lg = evaluate (LGBMRegressor, params)

def feature_importance(reg):
    plt.figure(figsize=(20,10))
    print(type(reg))
    df=pd.DataFrame(sorted(zip(X_train.columns, reg.feature_importances_)),columns=['features', 'values'])
    sns.barplot(x='values',y='features', data=df.sort_values (by='values', ascending=True))
    plt.show()

feature_importance (lg_reg)

submission = pd.read_csv('/content/sampleSubmission.csv')
submission.sample(5)

test.shape

submission.shape

pred = lg_reg.predict(test)
pred_exp= np.expm1(pred)
print(pred_exp)

submission.loc[:, 'count'] = pred_exp
submission

submission.to_csv(r'C:\Users\ankan\Music\result', sep='\t')